version: "3.8"

services:
  app:
    build: .
    container_name: lavava_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
    - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    image: jonasal/nginx-certbot:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d:ro
    environment:
      - CERTBOT_EMAIL=fcodenilson@gmail.com
      - DHPARAM_SIZE=4096
    depends_on:
      - app
    networks:
      - app_network
    restart: unless-stopped

volumes:
  db_data:
  certs:
  nginx_secrets:

networks:
  app_network:
