spring:
  datasource:
    url: "jdbc:h2:mem:dbtest"
    username: "sa"
    password: ""
    driver-class-name: "org.h2.Driver"

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: "create-drop"
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          import_files_sql_extractor: "org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor"
  
  sql:
    init:
      mode: "always"

  h2:
    console:
      enabled: true
      path: "/h2-console"

server:
  port: 8000
  servlet:
    context-path: "/api/v1"
