spring:
  datasource:
    url: "jdbc:h2:mem:dbtest"
    username: "sa"
    password: ""
    driver-class-name: "org.h2.Driver"

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: "/h2-console"

server:
  port: 8000
  servlet:
    context-path: "/api/v1"
